testrunner:
  image: codeguru/sinatra:1.4.7-ruby-2.3.1-alpine-3.4
  container_name: gem_test_runner
  command: bash -c "./scripts/container_loop.sh"
  volumes:
    - ./container_loop.sh:/scripts/container_loop.sh
    - ../:/gem_src

