require_relative 'exceptions/invalid_attribute_value_error'
require_relative 'exceptions/attribute_not_found_error'
require_relative 'exceptions/invalid_class_error'
require_relative 'exceptions/invalid_parse_value_error'